services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
